### ISSUE TITLE
What kind of hardware did you use?

### ISSUE THREAD

**Issue by two-trick-pony-NL** [ludwig7685/image-caption-generation-with-ai-and-api#3]
Hey! Nice work on the script. Very useful. Just wondering what kind of hardware you used for inference. I Don't have a particularly beefy server to work with.

**Comment by ludwig7685** [comment]
Hi! Im sorry for the late response because this here is the account where im only uploading woking code im kind off proud off 😅

I used the azure free trail - VM
4cpus 8 gb ram if im right.

The best VM that can stay up for about exactly a month with 100$ credits! 
( i used a education account )
